### ISSUE TITLE
[BUG] - Wrong landing rates being logged.

### ISSUE THREAD

**Issue by SilentDevCoPro** [invernyx/smartcars-3-bugs#300]
### Describe the bug

Rates logged:

1. 39fpm - Wrong rate, closer to 250
2. 24fpm - Wrong rate, closer to 250
3. 24fpm - Wrong rate, closer to 250
4. 374fpm - Close to real rate
5. 18fpm - Wrong rate, closer to 250
6. 87fpm - Close to real rate
7. 87fpm - Wrong rate this was roughly 320

Comparing rates with the X Plane 12 Landing Rates plugin, this plugin feels right with the numbers its giving me. I'm also not that good to consistently land below 100fpm.

There is also a pattern of low FPM landings, 24fpm, 24fpm, 87fpm, 87fpm. 

### How do you reproduce this bug?

This bug occurs from landing the plan and it being logged in the PIREP, out of the 7 landings I have logged above 5 are way off.

### Expected behavior

Variation of landing rates as shown by the Landing Rates plugin in x plane 12, I'v had some pretty hard landings and its giving me sub 100fpm.

### Screenshots

<img width="205" alt="Screenshot 2023-07-19 at 1 33 12 PM" src="https://github.com/invernyx/smartcars-3-bugs/assets/24499350/7f50b036-95ed-4e45-a456-0c3ad1f8c855">

### Operating system

M1 Mac, Ventura 13.4.1

### Community airline

qvirtual

### smartCARS Version

0.12.1

### Plugins installed

Chat, Flight Center, Flight Tracking, Logbook, Map, Simbrief

### Additional context

Another person on my VA has also noticed this bug, so it's not a one off.

**Comment by SilentDevCoPro** [comment]
<img width="178" alt="image" src="https://github.com/invernyx/smartcars-3-bugs/assets/24499350/12c13602-8517-4414-8907-ced8c0132eba">
More landing rates logged.

**Comment by GenericNerd** [comment]
Do you have low frame rates in X-Plane?

**Comment by SilentDevCoPro** [comment]
Reasonably good frame rates, running an M1 macbook ultra. Usually 30-60fps depending on the airport. Have the graphics also turned down to not drop frames as I fly on vatsim which requires 20+ fps.

**Comment by walkerairtrans** [comment]
I will add that my testers are seeing odd landing rates too -- and I've been able to monitor the "data" feed and I see a wide range of landing rates. I recall Colin saying that there was some kind of "multiple records of landing rates to generate an average landing rate" or something to that line.

We're on varying simulators, OS, and low end to high end workstations.

**Comment by GenericNerd** [comment]
> I will add that my testers are seeing odd landing rates too -- and I've been able to monitor the "data" feed and I see a wide range of landing rates. I recall Colin saying that there was some kind of "multiple records of landing rates to generate an average landing rate" or something to that line.
> 
> We're on varying simulators, OS, and low end to high end workstations.

Varying simulators and workstations? That is incredibly odd. We are taking the touchdown rate that FSUIPC gives us (or the descent rate in X-Plane). I'm not sure what other datapoints we could use for the touchdown rate, as we also supply the g-force.

> Rates logged:
>
> 39fpm - Wrong rate, closer to 250
> 24fpm - Wrong rate, closer to 250
> 24fpm - Wrong rate, closer to 250
> 374fpm - Close to real rate
> 18fpm - Wrong rate, closer to 250
> 87fpm - Close to real rate
> 87fpm - Wrong rate this was roughly 320

How are you able to tell which rate is correct or incorrect? Is there a program you're using to get the landing rate you're seeing?

**Comment by walkerairtrans** [comment]
> > I will add that my testers are seeing odd landing rates too -- and I've been able to monitor the "data" feed and I see a wide range of landing rates. I recall Colin saying that there was some kind of "multiple records of landing rates to generate an average landing rate" or something to that line.
> > We're on varying simulators, OS, and low end to high end workstations.
> 
> Varying simulators and workstations? That is incredibly odd. We are taking the touchdown rate that FSUIPC gives us (or the descent rate in X-Plane). I'm not sure what other datapoints we could use for the touchdown rate, as we also supply the g-force.

I thought I recall (in Teams) that Colin said there were multiple recordings of the landing rate taken and then combined to find an average? I did a test awhile back and I recorded multiple landing rates in the data feed but only 1 was selected--I also notice the "landed with landing rate XYZ" is delayed versus instant in SC2. I assumed that confirmed what I thought I heard from Colin? In that it records multiple rates and then does something..

Maybe that's not the case then. I could be wrong then.

**Comment by SilentDevCoPro** [comment]
I'm using a landing rates plugin in X-plane. The reason I believe they are correct or close to correct is that the feel of the landing matches what the plugin is showing, and what other people are getting. 

I honestly wish I was this much of a god at landing but my current average touchdown rate is 77fpm.
There is also no chance that my last 13 landings were 32fpm considering some were pretty rough.

<img width="172" alt="image" src="https://github.com/invernyx/smartcars-3-bugs/assets/24499350/50ea724e-61e6-434a-8501-6630d4595fde">

These were also done with a variety of aircraft at a variety of airports, which means I was experiencing anywhere from 30-80fps on landings.

**Comment by SilentDevCoPro** [comment]
Any updates on this issue? I had a 5000fpm landing rate last night at a high altitude airport from a butter smooth landing, any chance there can be a quick fix for a hard coded value until a fix is applied so it's no breaking planes for the VA?

**Comment by SilentDevCoPro** [comment]
Here is the log file from the flight I did today. 3x 5085 @ 24.6g landings, one was a cat 3 full auto landing, the other 2 were hand flown, one was purposefully floated to give a super butter landing.

`
17:24:23 | Touched down at -5085 fpm, 24.6g, 89 kts, 3 degrees pitch, 4 degrees bank, wind 027 at 30 kts with 14533 kgs of fuel (125kgs in flight)
-- | --
17:24:23 | On ground 1880 nm from planned arrival airport
17:24:40 | Going around at 7031 ft AGL, 134 kts, 12 degrees pitch, 0 degrees bank, wind 028 at 31 kts
17:24:48 | Pitch exceeded 20 degrees nose up
17:25:02 | Bank exceeded 35 degrees
17:25:11 | Gear lever raised at 139 kts
17:28:28 | Approach started at 14057 ft AGL with 1873 nm to go
17:28:40 | Flaps set to 0% at 184 kts
21:45:12 | Flaps set to 25% at 228 kts
21:47:42 | Flaps set to 50% at 195 kts
21:47:54 | Flaps set to 75% at 183 kts
21:48:00 | Flaps set to 100% at 175 kts
21:52:28 | Gear lever lowered at 127 kts
21:54:01 | On final at 1474 ft with 4 nm to go at 128 kts, 5 degrees pitch, -0 degrees bank
21:55:31 | Touched down at -5085 fpm, 24.6g, 126 kts, -1 degrees pitch, -1 degrees bank, wind 024 at 22 kts with 3974 kgs of fuel (10683kgs in flight)
21:55:43 | Flaps set to 75% at 107 kts
21:55:57 | Going around at 566 ft AGL, 152 kts, 12 degrees pitch, -0 degrees bank, wind 024 at 22 kts
21:56:20 | Gear lever raised at 140 kts
21:56:58 | Approach started at 2665 ft AGL with 2 nm to go
21:59:01 | Flaps set to 100% at 154 kts
22:04:16 | Gear lever lowered at 116 kts
22:08:49 | On final at 1458 ft with 4 nm to go at 127 kts, 5 degrees pitch, -0 degrees bank
22:10:25 | Touched down at -5085 fpm, 24.6g, 110 kts, -1 degrees pitch, -1 degrees bank, wind 024 at 22 kts with 3307 kgs of fuel (11351kgs in flight)
22:10:36 | Flaps set to 75% at 100 kts
22:10:47 | Going around at 534 ft AGL, 143 kts, 13 degrees pitch, 1 degrees bank, wind 024 at 22 kts
22:10:48 | Gear lever raised at 144 kts
22:11:46 | Approach started at 2658 ft AGL with 2 nm to go
22:18:13 | Gear lever lowered at 151 kts
22:22:22 | Flaps set to 100% at 148 kts
22:23:09 | On final at 1475 ft with 4 nm to go at 143 kts, 1 degrees pitch, -0 degrees bank
22:24:38 | Touched down at -5085 fpm, 24.6g, 132 kts, -0 degrees pitch, -1 degrees bank, wind 024 at 22 kts with 2698 kgs of fuel (11959kgs in flight)
22:25:11 | Flaps set to 75% at 26 kts
22:25:14 | Taxiing to gate, landed in 4564 ft
22:26:28 | Engine 1 Off
22:26:29 | Engine 2 Off


`

**Comment by GenericNerd** [comment]
This all happens in X-Plane? Is there a third tracker you use for landing rates? There is a (small) chance that one of the readings is wrong, but it's difficult to tell which one is incorrect.

**Comment by SilentDevCoPro** [comment]
@GenericNerd Very confused here, how is there a small chance that one of these readings is wrong? Even just landing within  zero feet per minute of each other is completely unlikely, and landing 3 times at 5085 fpm which is enough to destroy an aircraft after butter landings? I believe all of these rates are completely wrong.

These can also be confirmed by just looking at the feet per minute while landing which is shown in all aircraft, when you are on a 3 degree glide slope you go from 700-800fpm to 100-300fpm during the touchdown.

This is all occurring in x plane.

**Comment by GenericNerd** [comment]
> @GenericNerd Very confused here, how is there a small chance that one of these readings is wrong? Even just landing within zero feet per minute of each other is completely unlikely, and landing 3 times at 5085 fpm which is enough to destroy an aircraft after butter landings? I believe all of these rates are completely wrong.
> 
> These can also be confirmed by just looking at the feet per minute while landing which is shown in all aircraft, when you are on a 3 degree glide slope you go from 700-800fpm to 100-300fpm during the touchdown.
> 
> This is all occurring in x plane.

I'm not disagreeing with you, hence why I said small chance, but I want to be absolutely sure. Please try to let me know if another tracker gets the same information as smartCARS or as the landing plugin and we can go from there.

**Comment by SilentDevCoPro** [comment]
I have just gotten volanta working for a couple of landings, volanta seems to be +- 100fpm of the landing plugin, while smartcars was wildly off for most except one I did in the Colimata Concord in x plane 12.

- Landing plugin: 550 fpm
- Volanta: 500 fpm
- SC3: 483 fpm

However the next flight in an A320 I did a test landing, I intentionally did an extremely hard landing.
- Landing plugin: 1000+ fpm
- Voltanta: 1100 fpm
-  SC3: 83fpm

**Comment by bgiorgio0506** [comment]
> I have just gotten volanta working for a couple of landings, volanta seems to be +- 100fpm of the landing plugin, while smartcars was wildly off for most except one I did in the Colimata Concord in x plane 12.
> 
> - Landing plugin: 550 fpm
> - Volanta: 500 fpm
> - SC3: 483 fpm
> 
> However the next flight in an A320 I did a test landing, I intentionally did an extremely hard landing.
> - Landing plugin: 1000+ fpm
> - Voltanta: 1100 fpm
> -  SC3: 83fpm
> 

Did you bounce during the second landing ?

**Comment by SilentDevCoPro** [comment]
@bgiorgio0506 Unsure sorry, it didn't feel like a bounce but I wasn't focusing in on that. The readings of 80-90 fpm have come up from landings that definitely did not bounce though.

**Comment by walkerairtrans** [comment]
Just want to add that I'm now being told about this.
Had a pilot test 2 controlled flights, one with XPUIPC and one with XPLANE UDP -- XPUIPC recorded -151fpm and XPLANE UDP recorded 45fpm.

His previous 3 flights before he realized it were 41, 41, and 7 -- these were into fields where he's has negative landing rate before.

It seems that XP UDP is an issue.

Also noted landing log items are not making sense. Notice the wind is wrong.

[16:13:28] Touched down at 45 fpm, 1.1g, 110 kts, true heading 264, 0 degrees pitch, -0 degrees bank, wind 0-2 at -1 kts, fuel remaining 2624 kgs

**Comment by GenericNerd** [comment]
> Just want to add that I'm now being told about this. Had a pilot test 2 controlled flights, one with XPUIPC and one with XPLANE UDP -- XPUIPC recorded -151fpm and XPLANE UDP recorded 45fpm.
> 
> His previous 3 flights before he realized it were 41, 41, and 7 -- these were into fields where he's has negative landing rate before.
> 
> It seems that XP UDP is an issue.
> 
> Also noted landing log items are not making sense. Notice the wind is wrong.
> 
> [16:13:28] Touched down at 45 fpm, 1.1g, 110 kts, true heading 264, 0 degrees pitch, -0 degrees bank, wind 0-2 at -1 kts, fuel remaining 2624 kgs

We'll try to run some further tests in X-Plane and see if we can recreate this behaviour.

**Comment by SilentDevCoPro** [comment]
Update on the new highest landing rate achieved, 1 go around + 1 landing 20,000 fpm. In reality, it was 50fpm and 200fpm

<img width="1068" alt="image" src="https://github.com/invernyx/smartcars-3-bugs/assets/24499350/6fdbf199-3cd9-4e31-866d-1606f3b44809">

**Comment by Thien42** [comment]
The next release will include an update to the flight-tracking which I _believe_ should fix this problem. However I can't possibly test all possible scenarios by myself.

I will close this issue for now, but if you keep encountering inconsistencies _after the next update_, feel free to re-open it with as much information as you can.

**Comment by EpicHax7** [comment]
this issue is still present sc3 still calculates wrong landing rates i have pilots with 20 fps landing 500fpm with volanta  sc3 records 110fpm pilots with above 60 fps landing with 100fpm but sc3 records them at -46fpm
